=== midnightcoder/gracula/opencog/embodiment/RuleValidation/VirtualWorldData/VirtualWorld.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.vettalabs.com/petaverse"
            xmlns="http://www.vettalabs.com/petaverse"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="world-definition" type="WorldDefinitionData"/>

    <xsd:complexType name="WorldDefinitionData">
        <xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="entity-info" type="EntityList" 
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="indefinite-object-info" type="IndefiniteObjectList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="world-state-info" type="WorldStateData"
                             minOccurs="1" maxOccurs="1"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>    

    <xsd:complexType name="WorldStateData">
         <xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="near-info" type="NearList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="next-info" type="NextList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="owner-info" type="OwnerList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="moving-toward-info" type="MovingTowardList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="inside-fov-info" type="InsideFoVList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="has_said-info" type="HasSaidList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="relations-info" type="RelationList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="last-agent-action-info" type="LastAgentActionList"
                             minOccurs="1" maxOccurs="1"/>
                <xsd:element name="last-pet-schema-info" type="PetSchemaData"
                             minOccurs="1" maxOccurs="1"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute name="pet-id"   type="xsd:string" use="required"/>
        <xsd:attribute name="owner-id" type="xsd:string" use="required"/>
        <xsd:attribute name="pet-mode" type="xsd:string" use="required"/>
        <xsd:attribute name="agent-state" type="xsd:int" use="optional" default="1"/>
        <xsd:attribute name="action-repetition" type="xsd:int" use="required"/>
    </xsd:complexType>

    <!-- The indefinite objects list -->
    <xsd:complexType name="IndefiniteObjectList">
        <xsd:all>
            <xsd:element name="nearest_object" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_edible" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_movable" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_avatar" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_pet" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_small" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_moving" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_noisy" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_friendly" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_poo_place" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_pee_place" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_pickupable" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nearest_drinkable" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
           
            <xsd:element name="random_object" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_edible" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_movable" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_pickupable" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_drinkable" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_avatar" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_pet" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_small" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_moving" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_noisy" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_friendly" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_poo_place" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="random_pee_place" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>

            <xsd:element name="food_bowl" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="water_bowl" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="pet_home" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="pet_bowl" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="last_food_place" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
            <xsd:element name="exemplar_avatar" type="StringDataElementType" 
                minOccurs="0" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>
    
    <!-- The Entities list -->
    <xsd:complexType name="EntityList">
        <xsd:sequence>
            <xsd:element name="entity-object" type="EntityData" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="agent-object"  type="AgentData"  minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>


    <!-- The entity types allowed -->
    <xsd:simpleType name="EntityType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="pet"/>
            <xsd:enumeration value="object"/>
            <xsd:enumeration value="avatar"/>
            <xsd:enumeration value="accessory"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Entity properties -->
    <xsd:complexType name="EntityData">
        <xsd:attribute name="name"       type="xsd:string" use="required"/> 
        <xsd:attribute name="type"       type="EntityType" use="required"/> 
        
        <xsd:attribute name="noisy"      type="xsd:boolean" use="optional" default="false"/> 
        <xsd:attribute name="small"      type="xsd:boolean" use="optional" default="false"/> 
        <xsd:attribute name="edible"     type="xsd:boolean" use="optional" default="false"/> 
        <xsd:attribute name="movable"   type="xsd:boolean" use="optional" default="false"/> 
        <xsd:attribute name="drinkable"  type="xsd:boolean" use="optional" default="false"/> 
        <xsd:attribute name="pee_place"  type="xsd:boolean" use="optional" default="false"/> 
        <xsd:attribute name="poo_place"  type="xsd:boolean" use="optional" default="false"/> 
        <xsd:attribute name="pickupable" type="xsd:boolean" use="optional" default="false"/> 

        <xsd:attribute name="moving" type="xsd:boolean" use="optional" default="false"/> 
    </xsd:complexType>

    <!-- AgentData - extending EntityData -->
    <xsd:complexType name="AgentData">
        <xsd:complexContent>
            <xsd:extension base="EntityData">
               
                <xsd:all>
                <xsd:element name="hunger"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="thirst"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="energy"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="fitness" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="pee_urgency" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="poo_urgency" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>

                <xsd:element name="fear"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="hate"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="love"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="anger" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="pride" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="gratitude"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="happiness"  type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="excitement" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>

                <xsd:element name="excitability" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="playfulness" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="curiosity" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="friendliness" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="fearfulness" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="aggressiveness" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="appreciativeness" type="FloatDataElementType" minOccurs="1" maxOccurs="1"/>
                </xsd:all>

                <xsd:attribute name="novelty"  type="xsd:boolean" use="optional" default="false"/>
                <xsd:attribute name="learning"  type="xsd:boolean" use="optional" default="false"/>
                <xsd:attribute name="askedToTry"  type="xsd:boolean" use="optional" default="false"/>
                <xsd:attribute name="learnedTricks"  type="xsd:boolean" use="optional" default="false"/>
                <xsd:attribute name="requestedSchema"  type="xsd:boolean" use="optional" default="false"/>
                
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="FloatDataElementType">
        <xsd:attribute name="value" type="xsd:float" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="StringDataElementType">
        <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- Predicates data  -->
    <xsd:complexType name="SimplePredicateData">
        <xsd:attribute name="first"  type="xsd:string" use="required"/>
        <xsd:attribute name="second" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="HasSaidPredicateData">
        <xsd:attribute name="agent"  type="xsd:string" use="required"/>
        <xsd:attribute name="message"  type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="RelationPredicateData">
        <xsd:complexContent>
            <xsd:extension base="SimplePredicateData">
                <xsd:attribute name="name"  type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="NearList">
        <xsd:sequence>
            <xsd:element name="near" type="SimplePredicateData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="NextList">
        <xsd:sequence>
            <xsd:element name="next" type="SimplePredicateData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="OwnerList">
        <xsd:sequence>
            <xsd:element name="owns" type="SimplePredicateData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MovingTowardList">
        <xsd:sequence>
            <xsd:element name="moving-toward" type="SimplePredicateData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="InsideFoVList">
        <xsd:sequence>
            <xsd:element name="inside-fov" type="SimplePredicateData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RelationList">
        <xsd:sequence>
            <xsd:element name="relation" type="RelationPredicateData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="HasSaidList">
        <xsd:sequence>
            <xsd:element name="has-said" type="HasSaidPredicateData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Agent and Pet actions -->
    <xsd:complexType name="AgentActionData">
         <xsd:sequence>
            <xsd:element name="param" type="StringDataElementType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="agent"  type="xsd:string" use="required"/>
        <xsd:attribute name="action" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="PetSchemaData">
         <xsd:sequence>
            <xsd:element name="param" type="StringDataElementType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="schema"  type="xsd:string" use="required"/>
        <xsd:attribute name="result" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="LastAgentActionList">
        <xsd:sequence>
            <xsd:element name="last-action" type="AgentActionData" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== midnightcoder/gracula/opencog/embodiment/RuleValidation/VirtualWorldData/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<world-definition
    xmlns="http://www.vettalabs.com/petaverse"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vettalabs.com/petaverse VirtualWorld.xsd">
    <entity-info>
        <entity-object name="petHome" type="object" noisy="false" small="false"
                       edible="false" movable="false" 
                       drinkable="false" pee_place="false" poo_place="false"
                       pickupable="false" 
                       moving="false"/>
        <entity-object name="water01" type="object" noisy="false" small="true"
                       edible="false" movable="false" 
                       drinkable="true" pee_place="false" poo_place="false"
                       pickupable="false" 
                       moving="false"/>
        <entity-object name="meat" type="object" noisy="false" small="true"
                       edible="true" movable="true" 
                       drinkable="false" pee_place="false" poo_place="false"
                       pickupable="true" 
                       moving="false"/>
        <entity-object name="stick" type="object" noisy="false" small="true"
                       edible="false" movable="true" 
                       drinkable="false" pee_place="false" poo_place="false"
                       pickupable="true" 
                       moving="false"/>
        <entity-object name="barrilPoo" type="object" noisy="false" small="false"
                       edible="false" movable="false" 
                       drinkable="false" pee_place="false" poo_place="true"
                       pickupable="false" 
                       moving="false"/>
        <entity-object name="barrilPee" type="object" noisy="false" small="false"
                       edible="false" movable="false" 
                       drinkable="false" pee_place="true" poo_place="false"
                       pickupable="false" 
                       moving="false"/>
                      
        <entity-object name="wynx" type="avatar" noisy="false" small="false"
                       edible="false" movable="false" 
                       drinkable="false" pee_place="false" poo_place="false"
                       pickupable="false" 
                       moving="true"/>

        <agent-object name="fido" type="pet" noisy="false" small="false"
                       edible="false" movable="true" 
                       drinkable="false" pee_place="false" poo_place="false"
                       pickupable="false" 
                       moving="false" novelty="false" learning="false"
                       askedToTry="false"
                       learnedTricks="false" requestedSchema="false">

            <thirst value="0.5"/>
            <hunger value="0.5"/>
            <energy value="0.5"/>
            <fitness value="0.5"/>
            <pee_urgency value="0.5"/>
            <poo_urgency value="0.5"/>
            
            <fear value="0.4"/>
            <hate value="0.5"/>
            <love value="0.5"/>
            <anger value="0.5"/>
            <pride value="0.5"/>
            <gratitude value="0.5"/>
            <happiness value="0.5"/>
            <excitement value="0.5"/>

            <!-- maxie -->
            <curiosity value="0.7"/>
            <playfulness value="0.1"/>
            <fearfulness value="0.8"/>
            <friendliness value="0.6"/>
            <excitability value="0.6"/>
            <aggressiveness value="0.1"/>
            <appreciativeness value="0.1"/>
        </agent-object>
    </entity-info>

    <indefinite-object-info>
        <nearest_object  value="stick"/> 
        <nearest_edible  value="meat"/> 
        <nearest_movable value="stick"/>
        <nearest_pickupable value="stick"/> 
        <nearest_drinkable  value="water01"/>
        <nearest_avatar value="wynx"/> 
        <nearest_pet    value=""/> 
        <nearest_small  value="stick"/>
        <nearest_moving value="wynx"/>
        <nearest_noisy  value=""/> 
        <nearest_friendly  value=""/>
        <nearest_poo_place value="barrilPoo"/>
        <nearest_pee_place value="barrilPee"/>
        
        <random_object  value="petHome"/>
        <random_edible  value="meat"/>
        <random_movable value="stick"/>
        <random_pickupable value="meat"/> 
        <random_drinkable  value="water01"/>
        <random_avatar value="wynx"/>
        <random_pet    value=""/> 
        <random_small  value="stick"/>
        <random_moving value="wynx"/>
        <random_noisy  value=""/>
        <random_friendly  value=""/>
        <random_poo_place value="barrilPoo"/>
        <random_pee_place value="barrilPee"/>

        <food_bowl  value="meat"/>
        <water_bowl value="water01"/>
        <pet_home   value="petHome"/>
        <pet_bowl   value="meat"/>
        <last_food_place value=""/>
        <exemplar_avatar value=""/>
    </indefinite-object-info>

    <world-state-info pet-id="fido" owner-id="wynx" pet-mode="PLAYING_MODE"
                      agent-state="0" action-repetition="0">
        <near-info>
            <near first="wynx" second="fido"/>
            <near first="fido" second="wynx"/>
            <near first="fido" second="barrilPoo"/>
        </near-info>

        <next-info>
            <next first="wynx" second="fido"/>
            <next first="fido" second="wynx"/>
            <next first="fido" second="barrilPoo"/>
            <next first="fido" second="stick"/>
            <next first="stick" second="barrilPee"/>
        </next-info>

        <owner-info>
            <owns first="wynx" second="fido"/> 
        </owner-info>

        <moving-toward-info>
            <moving-toward first="wynx" second="fido"/>
        </moving-toward-info>

        <inside-fov-info>
            <inside-fov first="fido" second="meat"/>
            <inside-fov first="fido" second="barrilPoo"/>
        </inside-fov-info>

        <relations-info>
            <relation name="friend" first="fido" second="meat"/>
            <relation name="friend" first="fido" second="barrilPoo"/>
            <relation name="curiosity" first="fido" second="barrilPee"/>
            <relation name="curiosity" first="fido" second="water"/>
            <relation name="curiosity" first="fido" second="wynx"/>
            <relation name="curiosity" first="fido" second="stick"/>
            <relation name="curiosity" first="fido" second="petHome"/>
        </relations-info>

        <!-- not needed
        <has-said-info>
            <has-said agent="" message=""/>
        </has-said-info>

        <last-agent-action-info>
            <agent-action agent="" action="">
                <param value=""/>
            </agent-action>
        </last-agent-action-info>

        <last-pet-schema-info>
            <pet-schema schema="" result="">
                <param value=""/>
            </pet-schema>
        </last-pet-schema-info>
        -->
    </world-state-info>

</world-definition>
